Redo codeql-analysis.yml
First attempt on Monday June 2nd, 2025

diff --git a/.github/workflows/codeql-analysis.yml b/.github/workflows/codeql-analysis.yml
--- a/.github/workflows/codeql-analysis.yml
+++ b/.github/workflows/codeql-analysis.yml
@@ -1,61 +1,47 @@
-name: "CodeQL Scan"
+name: CodeQL
 
 on:
-  push:
   pull_request:
+    branches: [ "**" ]
 
 jobs:
   analyze:
-    name: Analyze
+    name: Run CodeQL Analysis
     runs-on: ubuntu-latest
+
     permissions:
       actions: read
       contents: read
       security-events: write
-    strategy:
-      fail-fast: false
-      matrix:
-        language: [ 'javascript-typescript' ]
+
     steps:
-    - name: Checkout repository
-      uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 #v4.2.2
-      
-    - name: Initialize CodeQL
-      uses: github/codeql-action/init@v3
-      with:
-        languages: ${{ matrix.language }}
-        queries: security-extended
-        db-location: ./codeql-db
-        
-    - name: Manual build step
-      run: |
-        npm ci
-        npm run build
-      
-    - name: Run CodeQL analysis and generate SARIF report
-      run: |
-        mkdir -p sarif-output
-        DB_DIR=./codeql-db
+      - name: Checkout repo
+        uses: actions/checkout@v3
 
-        echo "Using database: $DB_DIR"
-        
-        CODEQL="$(dirname "$(find /opt/hostedtoolcache/CodeQL -name codeql -type f | head -n 1)")/codeql"
-        echo "CodeQL binary: $CODEQL"
+      - name: Initialize CodeQL
+        uses: github/codeql-action/init@v3
+        with:
+          languages: java
 
-        "$CODEQL" database analyze \
-          --format=sarifv2 \
-          --output=sarif-output/codeql-report.sarif \
-          --threads=0 \
-          --rerun \
-          --ram=4096 \
-          "$DB_DIR" \
-          security-extended
+      - name: Attempt Autobuild
+        continue-on-error: true
+        uses: github/codeql-action/autobuild@v3
 
-          echo "SARIF output directory contents:"
-          ls -al sarif-output
-          
-    - name: Upload SARIF report
-      uses: actions/upload-artifact@v4
-      with:
-        name: codeql-sarif-report
-        path: sarif-output/codeql-report.sarif
+      - name: Perform CodeQL Analysis
+        uses: github/codeql-action/analyze@v3
+        with:
+            upload: false
+            output: results
+
+      - name: Check SARIF file exists
+        run: |
+          if [ ! -f results/java.sarif ]; then
+            echo "SARIF file not found"
+            exit 1
+          fi
+
+      - name: Upload SARIF artifact
+        uses: actions/upload-artifact@v4
+        with:
+            name: sast-report
+            path: results/java.sarif
